INSERT INTO USERS
SELECT DISTINCT USER_ID,FIRST_NAME,LAST_NAME,YEAR_OF_BIRTH,MONTH_OF_BIRTH,DAY_OF_BIRTH,GENDER
FROM keykholt.PUBLIC_USER_INFORMATION;


INSERT INTO FRIENDS
SELECT DISTINCT USER1_ID,USER2_ID
FROM keykholt.PUBLIC_ARE_FRIENDS;


CREATE SEQUENCE LOC_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE TRIGGER LOC_TRIGGER 
BEFORE INSERT ON CITIES
FOR EACH ROW 
BEGIN 
SELECT LOC_SEQUENCE.NEXTVAL INTO :NEW.CITY_ID FROM
DUAL;
END;
/
INSERT INTO CITIES(CITY_NAME,STATE_NAME,COUNTRY_NAME)
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
FROM keykholt.PUBLIC_USER_INFORMATION
UNION   
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY   
FROM keykholt.PUBLIC_USER_INFORMATION 
UNION   
SELECT DISTINCT EVENT_CITY,
EVENT_STATE, EVENT_COUNTRY   FROM keykholt.PUBLIC_EVENT_INFORMATION;
DROP SEQUENCE LOC_SEQUENCE;
DROP TRIGGER LOC_TRIGGER;


INSERT INTO USER_CURRENT_CITY
SELECT DISTINCT USER_ID,CITY_ID FROM keykholt.PUBLIC_USER_INFORMATION K
JOIN CITIES C ON (K.CURRENT_COUNTRY=C.COUNTRY_NAME AND K.CURRENT_STATE=C.STATE_NAME AND K.CURRENT_CITY=C.CITY_NAME);

INSERT INTO USER_HOMETOWN_CITY
SELECT DISTINCT USER_ID,CITY_ID FROM keykholt.PUBLIC_USER_INFORMATION K
JOIN CITIES C ON (K.HOMETOWN_COUNTRY=C.COUNTRY_NAME AND K.HOMETOWN_STATE=C.STATE_NAME AND K.HOMETOWN_CITY=C.CITY_NAME);



CREATE SEQUENCE PRO_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE TRIGGER PRO_TRIGGER 
BEFORE INSERT ON PROGRAMS
FOR EACH ROW 
BEGIN 
SELECT PRO_SEQUENCE.NEXTVAL INTO :NEW.PROGRAM_ID FROM
DUAL;
END;
/
INSERT INTO PROGRAMS(INSTITUTION,CONCENTRATION,DEGREE)
SELECT DISTINCT INSTITUTION_NAME,PROGRAM_CONCENTRATION,PROGRAM_DEGREE FROM keykholt.PUBLIC_USER_INFORMATION;
DROP SEQUENCE PRO_SEQUENCE;
DROP TRIGGER PRO_TRIGGER;

INSERT INTO EDUCATION
SELECT DISTINCT USER_ID, PROGRAM_ID, PROGRAM_YEAR FROM keykholt.PUBLIC_USER_INFORMATION K
JOIN PROGRAMS P ON (K.INSTITUTION_NAME=P.INSTITUTION AND K.PROGRAM_CONCENTRATION=P.CONCENTRATION AND K.PROGRAM_DEGREE=P.DEGREE);

INSERT INTO USER_EVENTS
SELECT DISTINCT EVENT_ID,EVENT_CREATOR_ID,EVENT_NAME,EVENT_TAGLINE,EVENT_DESCRIPTION,EVENT_HOST,EVENT_TYPE,EVENT_SUBTYPE,EVENT_LOCATION,
CITY_ID,EVENT_START_TIME,EVENT_END_TIME FROM keykholt.PUBLIC_EVENT_INFORMATION E
JOIN CITIES C ON (E.EVENT_COUNTRY=C.COUNTRY_NAME AND E.EVENT_STATE=C.STATE_NAME AND E.EVENT_CITY=C.CITY_NAME);

INSERT INTO ALBUMS
SELECT DISTINCT ALBUM_ID,OWNER_ID,ALBUM_NAME,ALBUM_CREATED_TIME,ALBUM_MODIFIED_TIME,ALBUM_LINK,ALBUM_VISIBILITY,COVER_PHOTO_ID 
FROM keykholt.PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOS
SELECT DISTINCT PHOTO_ID,ALBUM_ID,PHOTO_CAPTION,PHOTO_CREATED_TIME,PHOTO_MODIFIED_TIME,PHOTO_LINK
FROM keykholt.PUBLIC_PHOTO_INFORMATION;

INSERT INTO TAGS
SELECT DISTINCT PHOTO_ID,TAG_SUBJECT_ID,TAG_CREATED_TIME,TAG_X_COORDINATE,TAG_Y_COORDINATE
FROM keykholt.PUBLIC_TAG_INFORMATION;

